name: Swift

on:
  push:
    branches: [ main ]
    paths:
      - './MilliArt/MilliArt/swiftlint.yml'
      - '**/*.swift'
  pull_request:
    branches: [ main ]    
    paths:
      - './MilliArt/MilliArt/swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
