name: Swift

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/swift.yml'
      - './MilliArt/MilliArt/swiftlint.yml'
      - './MilliArt/MilliArt/Classes/*.swift'
    paths-ignore:
      - '.VIPER.xctemplate/'
  pull_request:
    branches: [ main ]    
    paths:
      - '.github/workflows/swift.yml'
      - './MilliArt/MilliArt/swiftlint.yml'
      - './MilliArt/MilliArt/Classes/*.swift'
    paths-ignore:
      - '.VIPER.xctemplate/'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ls
      - uses: norio-nomura/action-swiftlint@3.2.1
            
