name: Swift

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/swift.yml'
  pull_request:
    branches: [ main ]    
    paths:
      - '.github/workflows/swift.yml'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ls
      - uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --path MilliArt/
            
