name: Swift

on: [push, pull_request]

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --path MilliArt/ --strict
            
